server:
  port: 8761

eureka:
  instance:
    hostname: discoveryserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

spring:
  cloud:
    config:
      discovery:
        enabled: true
